version: '3.1'

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: balloon-shop
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
